### PR TITLE
update eslint config for parserOptions

### PR DESCRIPTION
**Pull request by mikehobi**
haven't tested...

http://eslint.org/docs/user-guide/configuring#specifying-parser-options

### CODE REVIEW

**Comment by kylpo** [comment]
pffff, haven't tested!? Would you, please? Just copy/paste it in your `node_modules`.

**Comment by mikehobi** [comment]
Looks to be working!

before...
before

after...
after

**Comment by mikehobi** [comment]
@kylpo might hold off on merging this. I'm getting another error similar to this:

https://github.com/eslint/eslint/issues/5552

Might need to add `sourceType: "module"` to the `parserOptions` config. Probably need to check and see what other things should be set.

**Comment by kylpo** [comment]
Dang, even made animated gifs! 🤗 

Cool, feel free to merge when you're happy with it. Just ping me so I can know when to release it.

**Pull request merged**
